// Banco de categorias, compartilhado pela Panelinha e pelo Cordel.
//
// Cada categoria: [nome, tipo, nível, palavras, cordel?]
//   tipo  — "direto" (coisas do mesmo tipo), "cultura" (o que a gente reconhece do Brasil),
//           "expressao" (completa a expressão), "trocadilho" (jogo com as letras)
//   nível — 1 a 4, do mais óbvio (amarelo) ao mais traiçoeiro (roxo)
//   palavras — todas as que cabem na categoria (quanto mais, melhor: é assim que o gerador
//           sabe quando uma palavra serviria em dois grupos e vira armadilha)
//   cordel — opcional: [pista, palavra-chave] para virar tema do Cordel
// Uma palavra pode estar em várias categorias. Escreva com acento; os jogos tiram o que precisam.
export const BANCO = [
  // ---------- direto ----------
  ["Frutas do Nordeste", "direto", 1, ["caju", "pitanga", "umbu", "seriguela", "cajá", "mangaba", "graviola", "jaca", "pinha", "acerola", "maracujá"]],
  ["Coisas do chimarrão", "direto", 1, ["cuia", "bomba", "erva", "térmica", "chaleira", "mateada", "galpão", "fogo", "prosa", "gaúcho", "geada", "manhã"], ["Roda de chimarrão", "MATEAMARGO"]],
  ["Bichos do Pantanal", "direto", 1, ["jacaré", "capivara", "onça", "tuiuiú", "sucuri", "ariranha", "piranha", "arara", "tamanduá", "cervo"]],
  ["Temperos", "direto", 1, ["alho", "cebola", "salsinha", "cebolinha", "coentro", "pimenta", "orégano", "cominho", "louro", "colorau", "manjericão", "noz-moscada"]],
  ["Partes do carro", "direto", 1, ["volante", "pneu", "freio", "embreagem", "capô", "porta-malas", "farol", "câmbio", "motor", "para-choque", "retrovisor"], ["Na oficina mecânica", "AUTOMOVEL"]],
  ["Peças de xadrez", "direto", 1, ["rei", "rainha", "torre", "bispo", "cavalo", "peão"]],
  ["Naipes e cartas", "direto", 2, ["copas", "espadas", "ouros", "paus", "valete", "dama", "coringa", "ás"]],
  ["Instrumentos de sopro", "direto", 1, ["flauta", "trompete", "saxofone", "clarinete", "trombone", "tuba", "gaita", "oboé", "fagote", "pífano"]],
  ["Coisas de praia", "direto", 1, ["areia", "onda", "canga", "biquíni", "concha", "guarda-sol", "protetor", "picolé", "chinelo", "maré", "cooler"]],
  ["Signos do zodíaco", "direto", 1, ["áries", "touro", "gêmeos", "câncer", "leão", "virgem", "libra", "escorpião", "sagitário", "capricórnio", "aquário", "peixes"]],
  ["Capitais do Nordeste", "direto", 2, ["recife", "salvador", "fortaleza", "natal", "maceió", "aracaju", "teresina", "joão pessoa", "são luís"]],
  ["Estados do Brasil", "direto", 1, ["bahia", "goiás", "pará", "acre", "amapá", "ceará", "paraná", "piauí", "sergipe", "alagoas", "maranhão", "roraima", "rondônia", "tocantins"]],
  ["Cortes de carne", "direto", 1, ["picanha", "maminha", "fraldinha", "alcatra", "costela", "cupim", "contrafilé", "patinho", "acém", "lagarto", "músculo"], ["Churrasco de domingo", "CHURRASCO"]],
  ["Tipos de pão", "direto", 1, ["francês", "baguete", "ciabatta", "sovado", "bisnaga", "broa", "pita", "brioche", "integral", "careca"]],
  ["Ervas de chá", "direto", 1, ["camomila", "hortelã", "boldo", "erva-doce", "cidreira", "capim-santo", "carqueja", "hibisco", "gengibre", "canela"]],
  ["Bichos que viram adjetivo", "direto", 2, ["anta", "burro", "zebra", "vaca", "galinha", "cobra", "lesma", "toupeira", "porco", "gata", "gato", "raposa", "baleia"]],
  ["Ferramentas", "direto", 1, ["martelo", "alicate", "serrote", "chave", "trena", "lixa", "furadeira", "torquês", "esquadro", "prumo", "talhadeira"]],
  ["Moedas do mundo", "direto", 2, ["real", "euro", "dólar", "peso", "iene", "libra", "rublo", "rúpia", "franco", "coroa", "yuan"]],
  ["Unidades de medida", "direto", 2, ["metro", "litro", "grama", "polegada", "milha", "légua", "palmo", "braça", "quilo", "arroba", "jarda", "pé"]],
  ["Animais da savana", "direto", 1, ["leão", "zebra", "girafa", "elefante", "hiena", "rinoceronte", "guepardo", "búfalo", "avestruz", "hipopótamo", "gnu"]],
  ["Aves do Brasil", "direto", 1, ["sabiá", "tucano", "canário", "curió", "coruja", "maritaca", "sanhaço", "beija-flor", "bem-te-vi", "joão-de-barro", "quero-quero", "seriema"]],
  ["Doces de festa", "direto", 1, ["brigadeiro", "beijinho", "cajuzinho", "casadinho", "camafeu", "trufa", "quindim", "bem-casado", "olho-de-sogra"]],
  ["Danças", "direto", 2, ["samba", "forró", "frevo", "xote", "baião", "tango", "valsa", "bolero", "lambada", "axé", "maxixe", "salsa", "vanerão"]],
  ["Cores", "direto", 1, ["vermelho", "amarelo", "verde", "azul", "roxo", "laranja", "rosa", "marrom", "cinza", "preto", "branco", "lilás", "bege", "vinho", "creme"]],
  ["Tecidos", "direto", 2, ["seda", "linho", "algodão", "veludo", "cetim", "jeans", "lã", "chita", "tricoline", "brim", "renda", "tule"]],
  ["Partes da casa", "direto", 1, ["sala", "cozinha", "quarto", "banheiro", "varanda", "sótão", "porão", "garagem", "quintal", "lavanderia", "corredor"]],
  ["Profissões", "direto", 1, ["médico", "padeiro", "pedreiro", "advogado", "dentista", "carteiro", "bombeiro", "garçom", "pintor", "piloto", "juiz", "cozinheiro"]],
  ["Esportes olímpicos", "direto", 2, ["vôlei", "judô", "remo", "esgrima", "tiro", "vela", "surfe", "boxe", "handebol", "ginástica", "natação", "atletismo", "skate"]],
  ["Planetas", "direto", 1, ["mercúrio", "vênus", "terra", "marte", "júpiter", "saturno", "urano", "netuno"]],
  ["Meses do ano", "direto", 1, ["janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"]],
  ["Dias da semana", "direto", 1, ["domingo", "segunda", "terça", "quarta", "quinta", "sexta", "sábado"]],
  ["Pedras preciosas", "direto", 2, ["rubi", "esmeralda", "diamante", "safira", "topázio", "ametista", "turmalina", "ágata", "jade", "opala", "quartzo"]],
  ["Árvores do Brasil", "direto", 2, ["ipê", "jacarandá", "araucária", "jatobá", "aroeira", "embaúba", "jequitibá", "mogno", "cedro", "angico", "pau-brasil", "paineira"]],
  ["Queijos", "direto", 2, ["minas", "prato", "coalho", "muçarela", "parmesão", "provolone", "gorgonzola", "brie", "cottage", "ricota", "colonial", "requeijão"]],
  ["Massas", "direto", 1, ["espaguete", "lasanha", "nhoque", "talharim", "penne", "fusilli", "capeletti", "ravióli", "canelone", "parafuso", "gravatinha"]],
  ["Bebidas quentes", "direto", 1, ["café", "chá", "chocolate", "quentão", "chimarrão", "capuccino", "mate", "leite"]],
  ["Coisas de escritório", "direto", 1, ["grampeador", "clipe", "caneta", "pasta", "agenda", "envelope", "carimbo", "etiqueta", "furador", "durex", "régua"]],
  ["Formas geométricas", "direto", 1, ["círculo", "quadrado", "triângulo", "losango", "cubo", "esfera", "cilindro", "pirâmide", "cone", "hexágono", "trapézio", "elipse"]],
  ["Insetos", "direto", 1, ["formiga", "abelha", "barata", "grilo", "joaninha", "mosca", "pulga", "cupim", "vespa", "besouro", "gafanhoto", "libélula", "mosquito"]],
  ["Peixes de água doce", "direto", 2, ["tilápia", "pintado", "pacu", "tambaqui", "dourado", "lambari", "traíra", "piranha", "tucunaré", "pirarucu", "jundiá", "surubim"]],

  // ---------- cultura ----------
  ["Turma da Mônica", "cultura", 2, ["mônica", "magali", "cebolinha", "cascão", "franjinha", "chico bento", "anjinho", "xaveco", "bidu", "sansão", "rosinha", "jeremias", "milena"]],
  ["Sítio do Picapau Amarelo", "cultura", 2, ["emília", "narizinho", "pedrinho", "visconde", "cuca", "saci", "rabicó", "quindim", "conselheiro", "tia nastácia", "dona benta"]],
  ["Gírias do Sul", "cultura", 2, ["bah", "tchê", "guri", "guria", "bergamota", "cacetinho", "piá", "capaz", "tri", "lagartear", "pila", "sinaleira", "cusco"]],
  ["Gírias do Nordeste", "cultura", 2, ["oxente", "arretado", "massa", "visse", "aperreio", "mangar", "abestado", "cabra", "macho", "painho", "bizu", "arengar"]],
  ["Gírias de Minas", "cultura", 3, ["uai", "trem", "sô", "nó", "cê", "trem bão", "quitanda", "arreda", "bobeira", "custoso"]],
  ["Lendas do folclore", "cultura", 1, ["saci", "curupira", "boitatá", "iara", "boto", "cuca", "caipora", "lobisomem", "mula", "mapinguari", "negrinho"]],
  ["Marcas que viraram nome de coisa", "cultura", 3, ["gilete", "xerox", "bombril", "durex", "cotonete", "isopor", "maizena", "danone", "chiclete", "jacuzzi", "post-it", "band-aid", "fórmica", "tupperware"]],
  ["Ritmos brasileiros", "cultura", 1, ["samba", "forró", "frevo", "maracatu", "axé", "pagode", "sertanejo", "baião", "xote", "choro", "bossa", "funk", "carimbó", "lambada", "vanerão"]],
  ["Times de futebol do Brasil", "cultura", 1, ["grêmio", "inter", "flamengo", "corinthians", "palmeiras", "santos", "vasco", "bahia", "sport", "cruzeiro", "fluminense", "botafogo", "juventude", "ceará"]],
  ["Personagens de Chaves", "cultura", 2, ["chaves", "quico", "chiquinha", "madruga", "florinda", "girafales", "barriga", "nhonho", "popis", "jaiminho", "bruxa", "clotilde"]],
  ["Comidas de festa junina", "cultura", 1, ["pamonha", "canjica", "pinhão", "quentão", "paçoca", "pipoca", "curau", "cocada", "pé-de-moleque", "milho", "rapadura"]],
  ["Coisas do carnaval", "cultura", 1, ["confete", "serpentina", "fantasia", "marchinha", "bloco", "trio", "máscara", "abadá", "frevo", "desfile", "glitter", "fantasia"]],
  ["Super-heróis", "cultura", 2, ["batman", "superman", "hulk", "thor", "flash", "aquaman", "robin", "tempestade", "wolverine", "ciclope", "homem-aranha"]],
  ["Biscoitos e bolachas", "cultura", 2, ["maisena", "maria", "água e sal", "recheado", "rosquinha", "wafer", "polvilho", "amanteigado", "cream cracker", "sequilho"]],
  ["Comidas de boteco", "cultura", 1, ["coxinha", "pastel", "torresmo", "bolinho", "kibe", "empada", "porção", "mandioca", "calabresa", "linguiça", "petisco"]],
  ["Brinquedos de antigamente", "cultura", 2, ["pião", "peteca", "bolinha de gude", "pipa", "ioiô", "bambolê", "carrinho de rolimã", "pega-varetas", "bilboquê", "amarelinha", "elástico"]],
  ["Programas de auditório", "cultura", 3, ["faustão", "silvio", "xuxa", "angélica", "gugu", "luciano", "raul gil", "chacrinha", "eliana", "serginho"]],
  ["Nomes de cachorro clássicos", "cultura", 3, ["rex", "totó", "bidu", "pingo", "lassie", "thor", "nina", "mel", "pretinha", "bob", "tobby", "duque"]],
  ["Coisas de vó", "cultura", 2, ["tricô", "novela", "bolo", "chá", "crochê", "terço", "bala", "caderninho", "naftalina", "paninho", "conselho"]],
  ["Produtos de padaria", "cultura", 1, ["sonho", "rosca", "broa", "bisnaga", "cacetinho", "pingado", "média", "carolina", "pão de queijo", "torrada", "bauru"]],
  ["Lanches de rua", "cultura", 1, ["churros", "pipoca", "pastel", "acarajé", "tapioca", "espetinho", "cachorro-quente", "milho", "algodão-doce", "crepe", "cuscuz"]],

  // ---------- completa a expressão ----------
  ["Pé de ___", "expressao", 3, ["moleque", "cabra", "meia", "valsa", "pato", "atleta", "chumbo", "galinha", "ouvido", "vento", "guerra", "chinelo", "pano", "serra", "manga", "feijão", "alface"]],
  ["Pagar ___", "expressao", 3, ["pato", "mico", "promessa", "conta", "pedágio", "língua", "boleto", "aluguel"]],
  ["Cara de ___", "expressao", 3, ["pau", "tacho", "paisagem", "fuinha", "anjo", "pastel", "sono", "bunda"]],
  ["___ de galinha", "expressao", 3, ["pé", "pele", "canja", "memória", "ovo", "pena", "voo", "asa", "coxa", "peito"]],
  ["Dor de ___", "expressao", 3, ["cotovelo", "cabeça", "barriga", "dente", "garganta", "ouvido", "estômago", "consciência", "corno", "cotovelo"]],
  ["Bicho de ___", "expressao", 3, ["pé", "goiaba", "estimação", "pelúcia", "seda"]],
  ["___ de ouro", "expressao", 3, ["bola", "coração", "mão", "boca", "chave", "medalha", "mina", "bodas", "bota", "luva"]],
  ["Saco de ___", "expressao", 3, ["pancada", "dormir", "batata", "lixo", "pão", "areia", "gatos", "papel", "estopa", "risada"]],
  ["Olho de ___", "expressao", 3, ["sogra", "gato", "boi", "peixe", "águia", "lince", "vidro", "boto", "tigre"]],
  ["Boca de ___", "expressao", 3, ["siri", "lobo", "urna", "fumo", "sapo", "forno", "leão", "caçapa", "fogo"]],
  ["Água de ___", "expressao", 3, ["coco", "colônia", "salsicha", "rosas", "torneira", "chuva", "poço", "cheiro", "batata"]],
  ["Ovo de ___", "expressao", 3, ["páscoa", "colombo", "codorna", "galinha", "pata", "avestruz", "chocolate", "dinossauro"]],
  ["Pão de ___", "expressao", 3, ["queijo", "forma", "mel", "ló", "açúcar", "batata", "milho", "centeio", "minuto", "alho"]],
  ["Cabeça de ___", "expressao", 3, ["vento", "bagre", "alho", "chave", "ponte", "área", "porco", "fósforo", "prego"]],
  ["Mão de ___", "expressao", 3, ["vaca", "obra", "pilão", "tinta", "onze", "direção", "fada", "ferro", "obra"]],
  ["Banho de ___", "expressao", 3, ["loja", "gato", "sol", "chuva", "lua", "sangue", "cheiro", "assento", "espuma", "mar"]],
  ["Casa de ___", "expressao", 3, ["praia", "campo", "câmbio", "força", "máquinas", "marimbondo", "botão", "ferreiro", "vó", "show"]],
  ["Ponto de ___", "expressao", 3, ["ônibus", "venda", "partida", "fuga", "vista", "encontro", "cruz", "bala", "interrogação", "exclamação"]],

  // ---------- trocadilho ----------
  ["Têm um bicho escondido", "trocadilho", 4, ["contrato", "concurso", "celular", "planta", "maranhão", "estatuto", "formulário", "cinema", "sapato", "galope", "retrato", "estouro", "cobrador", "arraial", "salvação", "jantar", "discurso", "barato"]],
  ["Têm uma parte do corpo escondida", "trocadilho", 4, ["presidente", "acidente", "respeito", "vendedor", "bocado", "testamento", "pernambuco", "abocanhar", "pelego", "dedal"]],
  ["Começam com um número", "trocadilho", 4, ["dezembro", "setembro", "novembro", "militar", "novela", "novelo", "umbigo", "umbanda", "cemitério", "milho", "tresloucado", "dezena", "setentrional"]],
  ["Sem a primeira letra viram outra palavra", "trocadilho", 4, ["parte", "cidade", "coração", "falta", "agosto", "abaixo", "evento", "acima", "prato", "brasa", "cobra", "grosa", "pisca", "galho", "festa", "lindo"]],
  ["Palíndromos", "trocadilho", 4, ["arara", "ovo", "radar", "reviver", "osso", "asa", "rever", "ralar", "reter", "salas", "matam", "anilina", "omissíssimo"]],
  ["Têm uma fruta escondida", "trocadilho", 4, ["chuva", "esperança", "namorado", "pescoço", "aracaju", "viúva", "véspera", "temperatura", "imperador", "fumaça", "clima", "luvas"]],
  ["Coisas que têm dentes", "trocadilho", 4, ["pente", "serrote", "zíper", "engrenagem", "alho", "garfo", "serra", "chave", "tubarão", "pá"]],
  ["Jogos do Dia", "cultura", 4, ["sando", "cordel", "novelo", "eclipse", "azulejo", "cortado", "panelinha", "termo", "spotle"]],
  ["Apelidos de craques", "cultura", 2, ["pelé", "zico", "kaká", "romário", "garrincha", "tostão", "sócrates", "cafu", "falcão", "didi", "neymar", "ronaldinho", "rivaldo", "bebeto"]],
  ["Jeitos de dizer dinheiro", "cultura", 3, ["grana", "bufunfa", "pila", "tutu", "verba", "cascalho", "pataca", "conto", "gaita", "bala", "dindim", "faz-me-rir", "trocado"]],
  ["Jeitos de chamar alguém de bobo", "cultura", 3, ["tanso", "bocó", "pateta", "mané", "palerma", "banana", "abobado", "tonto", "otário", "lesado", "pamonha", "anta"]],
  ["Apelidos da cachaça", "cultura", 3, ["pinga", "caninha", "branquinha", "cana", "marvada", "birita", "goró", "aguardente", "mé", "água-que-passarinho-não-bebe"]],
  ["Coisas que a gente descasca", "direto", 2, ["banana", "laranja", "ovo", "batata", "cebola", "alho", "mexerica", "abacaxi", "pinhão", "amendoim"]],
  ["Têm um nome de gente escondido", "trocadilho", 4, ["semana", "escrita", "arquivo", "todavia", "construir", "motivo", "elevador", "planalto", "bacana", "trevas", "família"]],
  ["Também são nomes de cores", "cultura", 4, ["laranja", "vinho", "creme", "salmão", "chocolate", "café", "mostarda", "gelo", "areia", "palha", "oliva", "chumbo", "caramelo", "rosa", "uva"]],
  ["Coisas que têm asa", "trocadilho", 4, ["xícara", "bule", "panela", "avião", "anjo", "caneca", "borboleta", "galinha", "frango", "chaleira"]],
  ["Coisas que têm boca", "trocadilho", 4, ["fogão", "túnel", "garrafa", "vulcão", "forno", "saco", "fornalha", "metrô", "lobo"]],
  ["Coisas que têm olho", "trocadilho", 4, ["agulha", "furacão", "batata", "peixe", "mágico", "sogra", "boi", "lince"]],
  ["Coisas que têm coroa", "trocadilho", 4, ["rei", "rainha", "abacaxi", "dente", "relógio", "princesa", "santo", "papa"]],
  ["Nomes que também são cidades", "trocadilho", 4, ["vitória", "natal", "palmas", "belém", "bonito", "valença", "regente", "esperança", "aparecida", "nazaré", "candelária", "sorriso", "felicidade"]],
];
