// Temas do Cordel: pista, palavra-chave (cruza o tabuleiro de um lado ao outro) e palavras
// do tema. O gerador escolhe, entre as palavras de cada tema, um grupo que soma 48 letras
// junto com a chave (o tabuleiro 6×8 usa todas as letras uma vez só). Acentos e ç somem
// no tabuleiro (como no Termo); aqui eles ficam para a leitura no fim do jogo.
export const TEMAS = [
  ["Na feira de domingo", "FEIRALIVRE", ["pastel", "caldo de cana", "banana", "tomate", "freguês", "barraca", "pechincha", "alface", "laranja", "abacaxi", "repolho"]],
  ["Hora do cafezinho", "CAFEZINHO", ["xícara", "açúcar", "filtro", "garrafa", "bule", "pires", "grão", "torra", "moedor", "colher"]],
  ["Debaixo do guarda-sol", "BEIRAMAR", ["areia", "onda", "canga", "biquíni", "protetor", "conchas", "maré", "mergulho", "cooler", "chinelo", "picolé"]],
  ["Arraiá", "FESTAJUNINA", ["quadrilha", "fogueira", "pamonha", "quentão", "pipoca", "bandeirinha", "canjica", "paçoca", "sanfona", "balão"]],
  ["Na roda", "CAPOEIRA", ["berimbau", "ginga", "atabaque", "pandeiro", "mestre", "meia-lua", "aú", "ladainha", "cordão", "esquiva"]],
  ["Mesa de sábado", "FEIJOADA", ["couve", "farofa", "laranja", "torresmo", "linguiça", "costela", "paio", "arroz", "caipirinha", "orelha"]],
  ["Debaixo das copas", "FLORESTA", ["jequitibá", "cipó", "bromélia", "orquídea", "samambaia", "musgo", "tronco", "raiz", "folhagem", "palmito", "ipê"]],
  ["Dá samba", "BATUCADA", ["surdo", "tamborim", "cuíca", "agogô", "repique", "pandeiro", "chocalho", "caixa", "apito", "reco-reco"]],
  ["Bichos do Pantanal", "PANTANEIRO", ["jacaré", "capivara", "onça", "tuiuiú", "sucuri", "ariranha", "piranha", "arara", "cervo", "tamanduá"]],
  ["Para a viagem", "BAGAGEM", ["mala", "mochila", "passaporte", "escova", "toalha", "casaco", "chinelo", "carregador", "pijama", "óculos"]],
  ["Recheio de bolo", "CONFEITARIA", ["brigadeiro", "doce de leite", "morango", "ganache", "coco", "nozes", "ameixa", "creme", "abacaxi", "ninho"]],
  ["No céu de noite", "ESTRELAS", ["lua", "cometa", "planeta", "galáxia", "cruzeiro", "órion", "satélite", "meteoro", "nebulosa", "vênus"]],
  ["Na caixa de ferramentas", "OFICINA", ["martelo", "alicate", "serrote", "chave", "prego", "parafuso", "trena", "lixa", "furadeira", "torquês"]],
  ["Frutas do Norte", "AMAZONIA", ["açaí", "cupuaçu", "bacuri", "tucumã", "pupunha", "taperebá", "buriti", "graviola", "guaraná", "camu-camu"]],
  ["Hora de brincar", "RECREIO", ["pião", "bolinha de gude", "amarelinha", "pipa", "peteca", "esconde", "corda", "pique", "bambolê", "elástico"]],
  ["No consultório", "MEDICO", ["receita", "jaleco", "termômetro", "consulta", "exame", "vacina", "pressão", "estetoscópio", "maca", "remédio"]],
  ["Cores do arco-íris", "ARCOIRIS", ["vermelho", "laranja", "amarelo", "verde", "azul", "anil", "violeta", "roxo", "índigo", "púrpura"]],
  ["Do pomar", "FRUTEIRA", ["manga", "goiaba", "jabuticaba", "caju", "pitanga", "acerola", "mamão", "carambola", "limão", "pêssego"]],
  ["Partes do corpo", "ANATOMIA", ["joelho", "cotovelo", "ombro", "tornozelo", "pescoço", "umbigo", "costas", "queixo", "testa", "canela"]],
  ["Em campo", "FUTEBOL", ["goleiro", "zagueiro", "escanteio", "pênalti", "drible", "trave", "chuteira", "apito", "lateral", "golaço", "torcida"]],
  ["Na cozinha", "PANELAS", ["fogão", "concha", "escumadeira", "frigideira", "tampa", "colher", "peneira", "ralador", "forma", "chaleira"]],
  ["Clima maluco", "TEMPORAL", ["chuva", "trovão", "relâmpago", "granizo", "ventania", "garoa", "neblina", "nuvem", "raio", "enchente"]],
  ["Bichos de casa", "ESTIMACAO", ["gato", "cachorro", "calopsita", "hamster", "peixe", "tartaruga", "coelho", "periquito", "jabuti", "porquinho"]],
  ["Na estante", "LIVRARIA", ["romance", "poesia", "conto", "crônica", "biografia", "fábula", "gibi", "enciclopédia", "novela", "dicionário"]],
  ["Viajando de trem", "ESTACAO", ["trilho", "vagão", "bilhete", "maquinista", "plataforma", "apito", "dormente", "locomotiva", "embarque", "relógio"]],
  ["Na mochila do acampamento", "ACAMPAMENTO", ["barraca", "lanterna", "fogueira", "saco de dormir", "cantil", "isqueiro", "repelente", "bússola", "marmita", "corda", "canivete"]],
  ["Pratos da Bahia", "COMIDABAIANA", ["acarajé", "vatapá", "moqueca", "caruru", "abará", "bobó", "cocada", "xinxim", "efó", "quindim"]],
  ["Coisas do Sul", "GAUCHO", ["chimarrão", "cuia", "bomba", "bombacha", "churrasco", "galpão", "pala", "erva", "laço", "coxilha", "guaiaca"]],
  ["Roupa de inverno", "AGASALHO", ["casaco", "cachecol", "luva", "gorro", "meia", "moletom", "jaqueta", "suéter", "bota", "pantufa"]],
  ["Instrumentos de corda", "VIOLAO", ["cavaquinho", "viola", "violino", "harpa", "bandolim", "baixo", "guitarra", "ukulele", "contrabaixo", "alaúde"]],
  ["No jardim", "CANTEIRO", ["rosa", "girassol", "margarida", "hortênsia", "regador", "minhoca", "adubo", "mangueira", "tulipa", "lírio", "cerca"]],
  ["Profissões de rua", "AMBULANTE", ["pipoqueiro", "sorveteiro", "jornaleiro", "carteiro", "gari", "camelô", "engraxate", "taxista", "guarda", "feirante"]],
  ["Doces de festa", "DOCINHOS", ["brigadeiro", "beijinho", "cajuzinho", "olho de sogra", "bicho de pé", "casadinho", "bem-casado", "trufa", "quindim", "camafeu"]],
  ["Hora de dormir", "SONINHO", ["travesseiro", "lençol", "cobertor", "pijama", "abajur", "colchão", "sonho", "ninar", "chupeta", "edredom"]],
  ["Na escola", "MATERIAL", ["lápis", "borracha", "caderno", "régua", "estojo", "apontador", "mochila", "cola", "tesoura", "compasso", "giz"]],
  ["Do mar", "OCEANO", ["polvo", "baleia", "golfinho", "tubarão", "medusa", "lagosta", "siri", "arraia", "estrela", "coral", "cavalo-marinho"]],
  ["Aves do Brasil", "PASSAROS", ["sabiá", "bem-te-vi", "tucano", "beija-flor", "joão-de-barro", "canário", "sanhaço", "curió", "coruja", "pica-pau", "maritaca"]],
  ["No circo", "PICADEIRO", ["palhaço", "malabarista", "trapézio", "mágico", "lona", "acrobata", "pipoca", "domador", "equilibrista", "picolé", "nariz"]],
  ["Formas", "GEOMETRIA", ["círculo", "quadrado", "triângulo", "losango", "cubo", "esfera", "cilindro", "pirâmide", "cone", "hexágono", "trapézio"]],
  ["Na padaria", "PAOZINHO", ["sonho", "rosca", "broa", "baguete", "croissant", "bisnaga", "queijo", "presunto", "pingado", "média", "torrada"]],
  ["Bota no prato", "TEMPEROS", ["alho", "cebola", "salsinha", "cebolinha", "coentro", "pimenta", "orégano", "cominho", "louro", "colorau", "manjericão"]],
  ["Lendas brasileiras", "FOLCLORE", ["saci", "curupira", "boitatá", "iara", "mula", "boto", "cuca", "lobisomem", "caipora", "negrinho"]],
  ["Nas alturas", "MONTANHA", ["pico", "cume", "trilha", "encosta", "rocha", "neve", "escalada", "mirante", "vale", "serra", "abismo"]],
  ["Sobre rodas", "TRANSPORTE", ["ônibus", "carro", "bicicleta", "patinete", "moto", "caminhão", "kombi", "metrô", "bonde", "carroça"]],
  ["Hora do banho", "BANHEIRO", ["sabonete", "xampu", "toalha", "chuveiro", "esponja", "espuma", "pente", "secador", "torneira", "patinho"]],
  ["Jogos de mesa", "TABULEIRO", ["xadrez", "dama", "dominó", "baralho", "dado", "truco", "ludo", "bingo", "pôquer", "canastra", "peão"]],
  ["Grandes rios", "AFLUENTES", ["amazonas", "paraná", "tocantins", "xingu", "tapajós", "negro", "madeira", "uruguai", "araguaia", "jari"]],
  ["Coisas de bebê", "ENXOVAL", ["fralda", "mamadeira", "chupeta", "babador", "mordedor", "carrinho", "chocalho", "body", "manta", "talco"]],
  ["Dentro do computador", "TECNOLOGIA", ["teclado", "mouse", "tela", "memória", "placa", "cabo", "bateria", "webcam", "chip", "senha"]],
  ["No cinema", "PIPOCA", ["ingresso", "tela", "poltrona", "trailer", "estreia", "legenda", "roteiro", "diretor", "elenco", "sessão"]],
  ["Na horta", "VERDURAS", ["alface", "rúcula", "couve", "agrião", "espinafre", "repolho", "chicória", "acelga", "brócolis", "almeirão"]],
  ["Cheiro de chuva", "PRIMAVERA", ["flor", "pólen", "abelha", "borboleta", "brisa", "botão", "ninho", "orvalho", "perfume", "jasmim"]],
  ["Copa do mundo", "SELECAO", ["camisa", "hino", "bandeira", "vuvuzela", "álbum", "figurinha", "chuteira", "taça", "torcida", "estádio"]],
  ["Gente da família", "PARENTES", ["avó", "avô", "tio", "tia", "primo", "prima", "sobrinho", "cunhado", "sogra", "padrinho", "neto", "madrinha", "enteado", "bisavó", "caçula", "irmão", "netinha", "genro"]],
  ["No mapa", "GEOGRAFIA", ["rio", "ilha", "lago", "baía", "cabo", "península", "deserto", "planície", "estreito", "golfo", "delta"]],
  ["Dia de faxina", "LIMPEZA", ["vassoura", "rodo", "pano", "balde", "detergente", "esponja", "flanela", "aspirador", "sabão", "pá", "lixeira"]],
  ["Danças do Brasil", "RITMOS", ["xote", "baião", "xaxado", "frevo", "maracatu", "samba", "axé", "lambada", "carimbó", "ciranda", "coco"]],
  ["Coisas redondas", "CIRCULOS", ["roda", "pizza", "moeda", "botão", "anel", "bola", "relógio", "prato", "pneu", "disco", "laranja"]],
  ["Bichos da fazenda", "CURRAL", ["vaca", "cavalo", "porco", "galinha", "ovelha", "cabra", "pato", "boi", "burro", "peru", "bezerro"]],
  ["Hora do lanche", "MERENDA", ["sanduíche", "suco", "biscoito", "iogurte", "fruta", "bolo", "pão de queijo", "achocolatado", "pipoca", "maçã", "torrada", "queijo", "banana", "salgado", "vitamina", "pastel"]],
  ["Pelo Nordeste", "SERTAO", ["mandacaru", "xique-xique", "caatinga", "vaqueiro", "gibão", "açude", "rapadura", "baião", "jegue", "cuscuz"]],
  ["Coisas de carnaval", "CARNAVAL", ["confete", "serpentina", "fantasia", "marchinha", "bloco", "trio", "máscara", "abadá", "frevo", "glitter", "desfile"]],
  ["Ofícios antigos", "ARTESAO", ["ferreiro", "sapateiro", "alfaiate", "oleiro", "marceneiro", "relojoeiro", "tecelão", "seleiro", "ourives", "funileiro"]],
  ["No escritório", "PAPELARIA", ["grampeador", "clipe", "caneta", "pasta", "agenda", "envelope", "carimbo", "etiqueta", "durex", "post-it", "furador"]],
  ["Sabores de sorvete", "SORVETERIA", ["flocos", "creme", "chocolate", "morango", "pistache", "coco", "limão", "napolitano", "maracujá", "passas"]],
  ["No hospital", "ENFERMARIA", ["maca", "soro", "curativo", "injeção", "plantão", "seringa", "gesso", "raio-x", "cadeira", "visita"]],
  ["Coisas do planeta", "NATUREZA", ["vulcão", "geleira", "cachoeira", "caverna", "duna", "recife", "pântano", "savana", "tundra", "cânion"]],
  ["Para se vestir", "GUARDAROUPA", ["camisa", "calça", "saia", "vestido", "blusa", "bermuda", "short", "jaqueta", "meia", "cinto"]],
  ["Hora da música", "ORQUESTRA", ["maestro", "batuta", "partitura", "violino", "flauta", "tuba", "oboé", "harpa", "clarinete", "trompa", "fagote"]],
  ["Corpo celeste", "SISTEMASOLAR", ["mercúrio", "vênus", "terra", "marte", "júpiter", "saturno", "urano", "netuno", "plutão", "lua"]],
  ["Bom dia!", "AMANHECER", ["despertador", "café", "pão", "escova", "banho", "jornal", "sol", "orvalho", "galo", "bocejo", "chinelo"]],
  ["Bichos que voam", "VOADORES", ["abelha", "morcego", "borboleta", "mosca", "libélula", "vespa", "joaninha", "mosquito", "besouro", "gafanhoto", "mariposa"]],
  ["Coisas de pescador", "PESCARIA", ["anzol", "isca", "vara", "molinete", "rede", "canoa", "boia", "chumbada", "samburá", "tarrafa", "linha"]],
  ["Paixão nacional", "NOVELA", ["capítulo", "vilão", "mocinha", "galã", "cena", "trama", "final", "elenco", "bordão", "reprise", "abertura"]],
  ["Na fazenda de café", "COLHEITA", ["terreiro", "saca", "peneira", "arábica", "grão", "secador", "lavoura", "cafezal", "tulha", "rastelo"]],
  ["Bebidas", "BEBERAGEM", ["suco", "refrigerante", "chá", "água", "vitamina", "garapa", "limonada", "mate", "cerveja", "vinho", "guaraná"]],
  ["Coisas de aniversário", "PARABENS", ["bolo", "vela", "balão", "presente", "convite", "brigadeiro", "chapéu", "lembrança", "festa", "palmas", "docinho"]],
  ["Arte de rua", "GRAFITE", ["muro", "spray", "mural", "tinta", "stencil", "rolo", "pixo", "lambe", "cores", "artista"]],
  ["Coisas de tecido", "COSTURA", ["agulha", "linha", "dedal", "botão", "zíper", "tesoura", "alfinete", "retalho", "molde", "bainha", "carretel"]],
  ["Ilhas e praias", "LITORAL", ["enseada", "restinga", "mangue", "falésia", "farol", "píer", "dunas", "recife", "orla", "maré", "baía"]],
  ["Animais da savana", "SAFARI", ["leão", "zebra", "girafa", "elefante", "hiena", "rinoceronte", "gnu", "guepardo", "búfalo", "avestruz", "hipopótamo"]],
  ["Na cozinha mineira", "QUITANDA", ["pão de queijo", "biscoito", "broa", "rosquinha", "bolo", "pamonha", "doce de leite", "goiabada", "queijo", "café"]],
  ["Tem no parque", "PRACINHA", ["balanço", "gangorra", "escorregador", "banco", "chafariz", "pombo", "pipoqueiro", "árvore", "coreto", "trepa-trepa"]],
  ["Pedras e cristais", "MINERAIS", ["quartzo", "ametista", "turmalina", "topázio", "esmeralda", "diamante", "ágata", "rubi", "safira", "jade", "granito"]],
  ["Na loja de brinquedos", "BRINQUEDOS", ["boneca", "carrinho", "bola", "pião", "ioiô", "quebra-cabeça", "pelúcia", "lego", "patinete", "cubo", "petecas"]],
  ["Hora de cozinhar", "RECEITA", ["picar", "refogar", "assar", "ferver", "temperar", "fritar", "bater", "misturar", "dourar", "grelhar"]],
  ["Árvores do Brasil", "ARVORES", ["ipê", "jacarandá", "pau-brasil", "araucária", "jatobá", "aroeira", "embaúba", "jequitibá", "mogno", "cedro", "angico"]],
  ["Doces de vó", "COMPOTA", ["goiabada", "marmelada", "cocada", "pé de moleque", "ambrosia", "rapadura", "canjica", "arroz-doce", "quindim", "pudim"]],
  ["Teatro", "ESPETACULO", ["cortina", "ator", "ensaio", "plateia", "camarim", "cenário", "figurino", "aplauso", "roteiro", "estreia", "bilheteria"]],
  ["Chuva de letras", "ALFABETO", ["vogal", "consoante", "acento", "til", "cedilha", "sílaba", "letra", "palavra", "frase", "verso", "rima"]],
  ["Bichos pequenos", "MIUDINHOS", ["formiga", "grilo", "joaninha", "minhoca", "caracol", "aranha", "pulga", "cupim", "tatuzinho", "lagarta", "vagalume"]],
]
